### ISSUE TITLE
Duda sobre como seleccionar algo de un csv

### ISSUE THREAD

**Issue by LpavonPe** [LpavonPe/Nota_Tecnica_Fianzas#1]
Hola @gerdm , estoy intentando crear un diccionario que incluya todos los datos necesarios y tengo la idea de crear un diccionario por ramo y subramo y me gustaria que dentro de estos crear un diccionario que sus llaves sean lo que aparece en el primer renglon de mi archivo csv, pero no logro hacerlo de una manera no manual.
Esto es lo que he intentado hasta ahora:
https://github.com/LpavonPe/Nota_Tecnica_Fianzas/blob/28b58975694f398854f32f71f40483917354f52f/Nota_tecnica.py#L19-L21
Gracias, Saludos

**Comment by gerdm** [comment]
Hola @LpavonPe.
Lo que te recomiendo es revisar la librería `pandas` para trabajar con `csv`s. En [este notebook](https://github.com/analysic-nabla/intro-python/blob/master/notas/lec10.ipynb) hay una introducción para que vayas revisando.

Puedes leer un archivo `csv` desde pandas como:
```python
import pandas as pd
df = pd.read_csv("{nombre_de_archivo}")
```
